---
- name: Converge
  hosts: all
  become: yes
  collections:
    - community.general
  tasks:
    - name: "Run role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
